### ISSUE TITLE
ncm-ncd pre and post actions

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-ncd#110]
This (very long) issue is a former page of the Trac wiki about an idea discussed a while ago. Not clear if this is still matching a use case... but a GH issue seems the best place to archive it!

------------------------
We want to be able to take actions before and after components are
executed, with no link to the profile. Use cases include:

-   Report the execution results to the monitoring right away.
-   Freezing and unfreezing services in the members of an HA setup.

Users should be able to specify the actions that need to be taken.
However, these actions will not receive any `$config`-like object, or
any profile representation. Access to the profile is restricted to
configuration modules.

## When hooks will run

We'll run hooks as part of the `--configure` process only. We'll run
them:

-   before any components run (`run-init`).
-   after all components have run (`run-finalize`).

We may discuss also hooks:

-   before the execution of each component.
-   after the execution of each component.

But I'll implement these two only if people show me '''immediate''' use
cases for them.

####  run-init

The `run-init` hook will receive no arguments. If it fails, it shall
abort the execution of any configuration modules, but `run-finalize`
will still run.

#### run-finalize

The `run-finalize` hook will receive the execution status as its only
argument. If it fails, `ncm-ncd` will exit with a special exit code.

### Specifying the hooks

We'll specify hooks in `/etc/ncm-ncd.conf`. They will look like this:

```
#!ini
run-init-hook = <hook-name>
run-finalize-hook = <hook-name>
```

### What a hook actually is

We have two options here. And I'll implement only one of them, what's
the preference of the community?

#### Option 1: Perl module

A Perl module inside, say, `NCD::Hooks` namespace. It provides
`run_init` and `run_finalize` methods.

#### Option 2: an executable

Perl is not the favourite language of many contributors, and they prefer
to be able to write their hooks in a different language. Any scripted
hook that requires arguments would receive them as a JSON object via
STDIN.

**Comment by ned21** [comment]
I believe this was implemented, as `--pre-hook` and `--post-hook` - cf. https://github.com/quattor/ncm-ncd/blob/master/src/main/scripts/ncm-ncd.pod ?

**Comment by jouvin** [comment]
@ned21 as said this is old stuff from the Trac wiki and I was not able to judge myself whether it was still relevant... thus this issue. But it may be that this is already implemented or no longer relevant... Feel free to say so!

**Comment by stdweird** [comment]
Main differences with what exists
* there is no `run_init` and/or `run_finalize`
* only scripts are allowed for `pre/post-hook`, no perl modules.

I'm assuming the original wiki page is an RFC rather than actual documentation, otherwise some code got removed/lost.

**Comment by jouvin** [comment]
Exactly, the original page was an RFC... thus the issue. May be worth reopening and rediscussing at a next workshop if this is worth doing something...

**Comment by jouvin** [comment]
Current implementation is considered enough for our current use cases... Closing this issue and waiting for someone to raise that the missing bits are important to implement...
