### ISSUE TITLE
hasFile() prevents component modules from being relocated

### ISSUE THREAD

**Issue by jrha** [quattor/ncm-ncd#116]
The expected location for externally packaged Perl modules varies with distribution and may change in future releases:
* EL6 and EL7 — [`/usr/share/perl5/vendor_perl`](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Developer_Guide/lib.details.html#idp14646592)
* Debian (and derivatives) — [`/usr/share/perl5`](https://www.debian.org/doc/packaging-manuals/perl-policy/ch-perl.html#s-paths)

Our current implementation [assumes](https://github.com/quattor/ncm-ncd/blob/0028c74638b76083f54e1b8b2bf1a03752281306/src/main/perl/ComponentProxy.pm#L26) that component modules are located in `/usr/lib/perl/NCM/Component`, while this is the case if the components are installed by our RPMs, it may not be if they are installed by other means.

Removing the call to `hasFile` in `_load` allows the module to be loaded from any of the standard paths without issue. I assume the original intent here was to detect a missing module before is was loaded, but the `eval` block that loads the module deals with that case.

For example, with the check removed and the dirperm component missing:
```
# quattor-configure --nodeps --noautodeps dirperm accounts

[INFO] NCM-NCD version 17.3.0 started by root at: Tue Jun 27 13:25:38 2017
[INFO] Using profile CID 1 name prod_cloud-domain
[INFO] Ignoring broken pre/post dependencies (--nodeps flag set)
[INFO] executing configure on components....


[INFO] running component: dirperm
---------------------------------------------------------
[ERROR] bad Perl code in NCM::Component::dirperm (/usr/lib/perl/NCM/Component/dirperm.pm): Can't locate NCM/Component/dirperm.pm in @INC (you may need to install the NCM::Component::dirperm module) (@INC contains: /usr/lib/perl /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl) at /usr/share/perl/5.18/Module/Load.pm line 27.
Can't locate NCM/Component/dirperm in @INC (@INC contains: /usr/lib/perl /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl) at /usr/share/perl/5.18/Module/Load.pm line 27.

[ERROR] cannot load component: dirperm
[ERROR] cannot execute configure on component dirperm

[INFO] running component: accounts
---------------------------------------------------------
[INFO] System has 28 accounts in 52 groups
[INFO] Committing 52 groups
[INFO] Committing 28 accounts
[INFO] configure on component accounts executed, 0 errors, 0 warnings

=========================================================

[INFO] Errors while configuringing dirperm (1)
[ERROR] 1 errors, 0 warnings executing configure
```

I'll open a PR shortly which removes `hasFile()` so we can discuss.

**Comment by stdweird** [comment]
@jrha so accounts.pm is found, but dirperm.pm isn't?

**Comment by jrha** [comment]
Yes. In the example above I installed accounts.pm in /usr/share/perl5/NCM/Component/, dirperm was not installed at all.

**Comment by jrha** [comment]
i.e.
```
# find /usr/share/perl5/NCM/Component/ | sort
/usr/share/perl5/NCM/Component/
/usr/share/perl5/NCM/Component/accounts.pm
/usr/share/perl5/NCM/Component/spma
/usr/share/perl5/NCM/Component/spma.pm
/usr/share/perl5/NCM/Component/spma/yumng.pm
/usr/share/perl5/NCM/Component/spma/yum.pm
```
