### ISSUE TITLE
14.10.0-rc4: strange false component errors reported during upgrade

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-ncd#29]
During upgrade from 14.10.0-rc3 to 14.10.0-rc4 (https://github.com/quattor/release/issues/65), on almost all the test nodes (5), during one of the 3 runs of `ncm-ncd` involved in the upgrade process, I got a strange report that `ncm-ncd` exited with status 255 indicating the failure of some configuration modules. Depending on the nodes, the configuration module list is varying (from one component to all) with a reason message empty. And looking at the component log, there was no run completed with errors logged...

I suspect a false report by `ncm-ncd`. I don't followed the recent changes to it (I think there were some). It's probably worth to have a look, even though this is a non critical error IMO, as in fact the configuration modules run successfully and at the next `ncm-ncd` run the exit status is ok.

**Comment by jrha** [comment]
We'll keep an eye out for this again during 14.12 upgrades and decide what to do after that.

**Comment by jrha** [comment]
@jouvin can you check for this while testing RCs for 15.2?

**Comment by jouvin** [comment]
Yes but after I have a working RC!!!

**Comment by jrha** [comment]
:smile: naturally.

**Comment by jouvin** [comment]
I have not seen the problem when upgrading systems (already 6) from 14.10.0 to 15.2.0-rc6... Probably we can close the issue at the time we release 15.2.0 and I'll reopen it if I see the problem again.

**Comment by jrha** [comment]
Excellent news.
