### ISSUE TITLE
errors occuring before running components are not logged

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-ncd#30]
If an error occurs in `ncm-ncd` before running a component, the error is displayed on `stdout` but is not logged through a reporter as it is not yet initialized (this is partly related to #23). As a result, the error is lost if `ncm-ncd` is not run interactively as `ncm-cdispd` now no longer logs `ncm-ncd` output... (see https://github.com/quattor/ncm-cdispd/issues/18.

**Comment by stdweird** [comment]
@jouvin how can i trigger these types of crashes?

**Comment by jouvin** [comment]
April 2018 workshop: very old issue, need to check if it is still relevant after all the changes undergone by `ncm-ncd`. Now that everything is wrapped into CAF::Process, it may be that there no issue left related to this and in this case, the issue should be closed.

**Comment by stdweird** [comment]
confirmed that `nmc-cdispd` logs everything
also confirmed that a manual inserted broken dependency is not logged by `ncm-ncd` (in `/var/log/ncm/ncd.log` or in the component log file.)

**Comment by stdweird** [comment]
i retested the issue.
inserting a unknown module (`use abcd;`) in `spma.pm` reports the failure in the `ncd.log` file
inserting a unknown module in `spma/yum.pm` reports failure in `component-spma.log`

so there is no issue afaik
