### ISSUE TITLE
refine ComponentProxy _load method check for new method

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-ncd#43]
The current check in `_load` is very broad. We can refine the test (eg test for subclass from `NCM::Component`), but this might break backwards compatibility (since currently anything with a new method is allowed)

**Comment by stdweird** [comment]
@ned21 you probably have some ideas :smile:

**Comment by stdweird** [comment]
@ned21 any ideas in the meantime?

**Comment by ned21** [comment]
Good ideas for how to test complex internal methods is normally where I defer to @gombasg :)

What's the actual problem you are trying to solve here? If you just want to limit the scope for Component authors to make mistakes then requiring components to be a subclass of NCM::Component seems reasonable, although I believe we also need to allow sub-classes of other components? (e.g. we have a special-links component which does some magic to invoke the symlink component under a different namespace).

Do we need anything else?

**Comment by stdweird** [comment]
i don't know. i think this issue was opened in response to https://github.com/quattor/ncm-ncd/pull/42#discussion_r28651563

subclasses of components will always be subclasses of `NCM::Component` i think.

**Comment by ned21** [comment]
So to summarise:
1. _load doesn't enforce very much
2. because of (1) there's not much to unit test

Adding better unit tests means implementing (1), which in turn may break people running "private" configuration modules that do not comply with whatever rules we apply. 

So, do we really want more constrained behaviour? If someone wants to write the code I can check it against our internal modules but I wonder if this is yak shaving?

**Comment by stdweird** [comment]
@ned21 we could test for a method `Configure` or one of its friends (if it inherits from `NCM::Component` it will have it all of them, if not, well at oeast one should exists otehrwsie `ncm-ncd` can't do much).
but i'm also not sure it adds much, so i'm ok with doing nothing :smile:

**Comment by ned21** [comment]
Agree with checking there's a Configure method, the closing this one out.
