### ISSUE TITLE
Tests failing, unsure of the root cause

### ISSUE THREAD

**Issue by jrha** [quattor/ncm-ncd#56]
Failed running `build_all_repos.sh` (as root) on SL6, repeatable by running `mvn test` in the repository.

Prototype mismatch?
ignore-errors-from-dependencies: no such variable?

Full output [in a private gist](https://gist.github.com/jrha/c059635b55bc2bfb4728).

Any ideas?

**Comment by jrha** [comment]
@stdweird this isn't caused by [removing prototypes from CAF](https://github.com/quattor/CAF/pull/137) is it?

**Comment by jrha** [comment]
Probably not, testing against CAF with protoypes back in doesn't help.

**Comment by stdweird** [comment]
no, tests run fine on my laptop. i'll try to reproduce.

**Comment by stdweird** [comment]
tests fail accoring to output due to
```


#   Failed test 'No statesfiles dir exists (target/statefiles)'
#   at src/test/perl/component-proxy-list.t line 288.
# WARN state component mytestcomponent filename target/statefiles/mytestcomponent is inappropriate

#   Failed test 'states dir not created in case of failure'
#   at src/test/perl/component-proxy-list.t line 292.

#   Failed test 'No statesfiles dir exists (/root/quattordev/repos/ncm-ncd/target/statefiles)'
#   at src/test/perl/component-proxy-list.t line 296.
```

@jrha you do a `mvn clean` first right?

**Comment by stdweird** [comment]
can you make output with `QUATTOR_TEST_LOG_CMD_MISSING=1 QUATTOR_TEST_LOG_CMD=1 QUATTOR_TEST_LOG_DEBUGLEVEL=3 mvn clean test`

**Comment by jrha** [comment]
Yup `mvn clean test`.
Running again now.

**Comment by jrha** [comment]
Done, still fails, I've updated the gist with the output.

**Comment by jrha** [comment]
On a whim I updated the built tools and it passes, hmm.

**Comment by jrha** [comment]
Running `build_all_repos` again with #57 merged.

**Comment by jrha** [comment]
Got past ncm-ncd, failing on configuration-modules-core now.
