### ISSUE TITLE
ncm-ncd 16.6.0-rc3: log of last component run not flushed until ncm-ncd is restarted

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-ncd#66]
I observed during upgrade to 16.6.0-rc3 that the lines in `ncm-spma` log file corresponding to last `ncm-spma` run by `ncm-cdispd` were missing in the log file. To get the lines in the file, I had to either start a new deployment or restart `ncm-cdispd` (both resulting in a new run of `ncm-ncd`).

Probably a side effect of #64. May be good to fix it or revert #64 before releasing [16.6.0-rc3](https://github.com/quattor/release/issues/250), even if not strictly speaking a showstopper...

**Comment by stdweird** [comment]
@jouvin if it is easy to reproduce, you can test it with #64 reverted?
but i doubt this is related.
is the output also missing for other components? and was there a lot of output? or some other anomaly?
if you can reproduce it, a full `--debug 5` run is welcome. both the `ncm-ncd --co spma --debug 5 >& out` as well as the spma log file.

**Comment by jouvin** [comment]
Apologies, completely wrong diagnosis... See #69.
