### ISSUE TITLE
16.8.0 on SL5: uninitialized value in ComponentPRoxy

### ISSUE THREAD

**Issue by jouvin** [quattor/ncm-ncd#75]
On our SL5 systems, running `ncm-spma` manually (using `ncm-ncd`), I got several liines:

```
Use of uninitialized value in list assignment at /usr/lib/perl/NCD/ComponentProxy.pm line 520.
```

Unfortunately this is not in any log file... this is why we missed it. I have not been able to reproduce it on SL6 machines, so I guess this is specific to SL5... As far as I can say this seems harmless but I am not sure...

**Comment by stdweird** [comment]
run it with debug 5 and capture stdout/stderr, so we can see when this is generated. also, what is on line 520 in componentproxy?

**Comment by jouvin** [comment]
Line 520 is:
```
   %SIG = %SIG_ORIG;
```
I attach the log, not sure if it really helps...
[spma.log.gz](https://github.com/quattor/ncm-ncd/files/484510/spma.log.gz)

**Comment by jouvin** [comment]
This seems to happen only with `ncm-spma`. But this may be just because this is the first component run...

**Comment by stdweird** [comment]
if it is easy to reproduce, can you insert 
```perl
use Data::Dumper;
print Dumper(\%SIG_ORIG);
```
before line 20 and send the output?

**Comment by jrha** [comment]
Seems to have stalled, but should still be fixed, bumping due to lack of time this cycle.
