### ISSUE TITLE
reset CLIST in ComponentProxyList _initialize?

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-ncd#76]
why does this even work?
https://github.com/quattor/ncm-ncd/blob/master/src/main/perl/ComponentProxyList.pm#L766

should be removed or i don't understand how the code works

**Comment by ned21** [comment]
I imagine it "works" in normal operation because ```$self->_getComponents();``` never returns undef and the code never executes? But I agree I don't see the reason for ```$self->{CLIST} = []``` before that call. Can you set something up to trigger that code path and see what happens?

**Comment by jouvin** [comment]
I tend to agree with @ned21: both L761 and L766 /could/should be removed.
