### ISSUE TITLE
components that have errors that are downgraded to warnings, leave empty statefile

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-ncd#77]
very likely unintended behaviour

**Comment by jouvin** [comment]
Clearly not very good... and matching a problem I have seen on some machines at LAL. Could you be a little bit more specific about what triggers the problem?

**Comment by stdweird** [comment]
this is a cornercase of https://github.com/quattor/ncm-cdispd/issues/35, you have to run `ncm-ncd` with `--ignore-errors-from-dependencies` which is done eg by AII the first time it runs spma.
@jouvin you are probably observing the touched statefiles from inactive components by ncm-cdispd, which would occur more frequently.
