### ISSUE TITLE
EL7: exception when parsing version string

### ISSUE THREAD

**Issue by ned21** [quattor/ncm-ncd#78]
```
# ncm-ncd --configure --all
 
[INFO] NCM-NCD version 16.8.0 started by root at: Tue Sep 20 12:11:54 2016
updated /var/lib/ccm/profile.3/ccm-active-profile.3-20593
[INFO] No components specified, getting all active ones.
[ERROR] component afsclt has invalid version from config 16.6.0 (bug in profile?): Invalid version format (non-numeric data) at /usr/lib/perl/NCD/ComponentProxy.pm line 267.
 
[ERROR] Failed to create ComponentProxy for component afsclt
[ERROR] No components to dispatch.
[ERROR] Uncaught exception!
[ERROR] Calling stack is:
                LC::Exception::throw_error called at /usr/lib/perl/CAF/Object.pm line 106
 
                CAF::Object::new called at /usr/lib/perl/NCD/ComponentProxyList.pm line 661
 
                NCD::ComponentProxyList::get_proxies called at /usr/lib/perl/NCD/ComponentProxyList.pm line 745
 
                NCD::ComponentProxyList::_getComponents called at /usr/lib/perl/NCD/ComponentProxyList.pm line 777
 
                NCD::ComponentProxyList::_initialize called at /usr/lib/perl/CAF/Object.pm line 94
 
                CAF::Object::new called at /usr/sbin/ncm-ncd line 580
 
[ERROR] *** cannot instantiate class: NCD::ComponentProxy
 
                (in cleanup) finishing... at /usr/sbin/ncm-ncd line 425 during global destruction.
```

@ajf8 tracked this down to a bug in the perl  version module (shipped by Red Hat) which parses version strings. It used to be written in pure perl, but at some point they did a preferred C implementation, with fallback to the perl one. Which is why this works around it:
 
```# mv /usr/lib64/perl5/vendor_perl/auto/version/vxs/vxs.so{,.off}```
 
It’s somehow related to tainted data (which the version string is). I guess the new C implementation of version.pm is unable to handle tainted strings properly. [This will be reported to RH]
 
Turning off taint mode in the ncm-ncd executable works around the issue, but I think untainting the version using a regex in ComponentProxy.pm should be a better workaround.

**Comment by stdweird** [comment]
i tought we untainted the version already, because we had this issue in some other perl code.
@ned21 what the perl version rpm? (it's a bit odd we haven't seen this yet on our systems)

**Comment by ned21** [comment]
$ rpm -qf /usr/lib64/perl5/vendor_perl/version.pm
perl-version-0.99.07-2.el7.x86_64

**Comment by stdweird** [comment]
with 
```
[root@node2601 ~]# rpm -q perl
perl-5.16.3-286.el7.x86_64
[root@node2601 ~]# rpm -q perl-version
perl-version-0.99.07-2.el7.x86_64
```
however, we do not see the crash on centos7

**Comment by NZJourneyMan** [comment]
Reproducer is:
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

$ rpm -q perl perl-version
perl-5.16.3-286.el7.x86_64
perl-version-0.99.07-2.el7.x86_64

$ cat reproducer.pl 
#!/usr/bin/perl
use version;
version->new(`echo 1.2.3`);

$ ./reproducer.pl 
Version string '%s' contains invalid data; ignoring: '%s'1.2.3
```

**Comment by stdweird** [comment]
@NZJourneyMan hmm, that's different (also, without `-t` or `-T`, there should be no issue). can you try the commands below?
```
[root@node2601 ~]# perl -e 'use version;version->new(`echo 1.2.3`)'
[root@node2601 ~]# perl -Tw -e 'use version;version->new(`echo 1.2.3`)'
Insecure $ENV{PATH} while running with -T switch at -e line 1.
[root@node2601 ~]# perl -Tw -e '$ENV{PATH}="/usr/bin";use version;version->new(`echo 1.2.3`)'
Invalid version format (non-numeric data) at -e line 1.
[root@node2601 ~]# perl -Tw -e '$ENV{PATH}="/usr/bin";use version;$a=`echo 1.2.3`; print $a,"\n";version->new($a)'
1.2.3

Invalid version format (non-numeric data) at -e line 1.
```

**Comment by stdweird** [comment]
@ned21 @NZJourneyMan @ajf8 please try rpm https://jenkins1.ugent.be/job/ncm-ncd-pr-builder/lastSuccessfulBuild/org.quattor.cfg.module$ncm-ncd/

**Comment by NZJourneyMan** [comment]
The errors are slightly different when run from the command line. Hence why I used a small script eariler:
```
$perl -e 'use version;version->new(`echo 1.2.3`)'
$perl -we 'use version;version->new(`echo 1.2.3`)'
Version string '1.2.3
' contains invalid data; ignoring: '
' at -e line 1.

$perl -Tw -e 'use version;version->new(`echo 1.2.3`)'
Insecure $ENV{PATH} while running with -T switch at -e line 1.

$perl -Tw -e '$ENV{PATH}="/usr/bin";use version;version->new(`echo 1.2.3`)'
Version string '1.2.3
' contains invalid data; ignoring: '
' at -e line 1.

$perl -Tw -e '$ENV{PATH}="/usr/bin";use version;$a=`echo 1.2.3`; print $a,"\n";version->new($a)'
1.2.3

Version string '1.2.3
' contains invalid data; ignoring: '
' at -e line 1.
```
However the new line at end of 1.2.3 made me wonder. Adding a chomp seems to have fixed it the problem:
```
perl -Tw -e '$ENV{PATH}="/usr/bin";use version;$a=`echo 1.2.3`;chomp $a;version->new($a)'
```

Working with @ajf8 yesterday it was clear that either renaming vxs.so or running without -T cleared the problem, so this looks like a slight difference between the pure perl and the C implementation in taint handling.

**Comment by stdweird** [comment]
@NZJourneyMan the fix in https://github.com/quattor/ncm-ncd/pull/79 (with the rpm in the jenkins url above) should untaint the version data from the config tree. can you try that?

**Comment by stdweird** [comment]
@NZJourneyMan to trigger the issue wrt tainting, do
```
echo -n 1.2.3 > /tmp/version && perl -T -e 'use warnings;use strict;use version;open(FH,"/tmp/version");$a=join("",<FH>);eval {version->new($a)}; print "fail$@\n"';
```
with and without `-T`

we get
```
[root@node2601 ~]# echo -n 1.2.3 > /tmp/version && perl -e 'use warnings;use strict;use version;open(FH,"/tmp/version");$a=join("",<FH>);eval {version->new($a)}; print "fail$@\n"';
fail
[root@node2601 ~]# echo -n 1.2.3 > /tmp/version && perl -T -e 'use warnings;use strict;use version;open(FH,"/tmp/version");$a=join("",<FH>);eval {version->new($a)}; print "fail$@\n"';
failInvalid version format (non-numeric data) at -e line 1, <FH> line 1.

```
not everything is considered tainted in perl, but reading data from files typically is

**Comment by ned21** [comment]
Confirmed that fixes it.

**Comment by NZJourneyMan** [comment]
As ned21 said, that fixes it. 

Also I discovered that I was trying to create the reproducer on a box that had vxs.so renamed, hence the odd results - it was working as it should have. :/
