### ISSUE TITLE
ncm-ncd --configure --all should conflict with any components specified on commandline

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-ncd#80]
Currently, when `--all` is passed together with one or more components, the components specified win.
Should either give a warning or failure.

**Comment by piojo** [comment]
Current behaviour is that `ncm-ncd --co --all spma` would run spma only, which is surprising.  The command-line parser should diagnose this case and refuse to run.

**Comment by jouvin** [comment]
As per discussion at the workshop,, `--configure` (or `--unconfigure`) should remain required with `-all`.
