### ISSUE TITLE
`ncm-ncd` run components in clean enviroment

### ISSUE THREAD

**Issue by stdweird** [quattor/ncm-ncd#85]
`ncm-ncd` runs the component in a almost unmodified environment, it would be interesting for reproducabiliy that this is seriously reduced (when run outside `ncm-cdispd`).

What should be allowed in env?
* PATH ->already the case
* LD_LIBRARY_PATH, LDPRELOAD
* LANG,LC,... -> these can be set based on the login session of the user that runs it (or (re)starts ncm-cdispd?)

we could provide an new option to allow existing environment, and enable it by default to test out the effect of a stricter environment

**Comment by jouvin** [comment]
Suggestion is to determine what is the environment created by `service` for `ncm-cdispd` and use (hard code it in ncm-ncd) the same restricted environment as it is know to work with all components.

**Comment by stdweird** [comment]
we have this one on of our EL6 nodes
```
# strings /proc/`pgrep ncm-cdispd`/environ
TERM=linux
PATH=/sbin:/usr/sbin:/bin:/usr/bin
PWD=/
LANG=en_US.UTF-8
SHLVL=2
_=/usr/sbin/ncm-cdispd
```

the LANG is the system default, we did not specify it, i guess if the LANG variable is not set, it will pick it up also. if we specify it, we should probably use `C` or `en_US.UTF-8`.
none of the the other variables are required, i think PATH is reset anyway in the perl code.

so basically, i'll try to run `ncm-ncd` with only PATH defined and see what breaks.
